<?php
session_start();              //session is started for storing captcha phrase

define('captcha_numbers',6);    // total characters of captcha image
define('captcha_width',150);      // width of captcha
define('captcha_height',30);     // height of captcha

$pass_phrase="";

/* Random numbers between 97 to 122 will be generated by using rand() and converted into ascii characters using chr()*/
for($i=0;$i<captcha_numbers;$i++)
  $pass_phrase.=chr(rand(97,122));            


$_SESSION['sys_captcha']=$pass_phrase;  //storing captcha phrase on server

$img=imagecreatetruecolor(captcha_width,captcha_height);
$bg_color=imagecolorallocate($img,255,255,255);
$text_color=imagecolorallocate($img,0,0,0);
$graphic_color=imagecolorallocate($img,64,64,64);

imagefilledrectangle($img,0,0,captcha_width,captcha_height,$bg_color);


//some lines will be displayed on text so that image will look somewhat distored
for($i=0;$i<2;$i++){
imageline($img,0,rand()%captcha_height,captcha_width,rand()%captcha_height,$graphic_color);
}


//some dots will be displayed on text so that image will look somewhat distored
for($i=0;$i<50;$i++){
imagesetpixel($img,rand()%captcha_width,rand()%captcha_height,$graphic_color);
}

imagestring($img,9,captcha_width-90,captcha_height-20,$pass_phrase,$text_color);


/* Note how captcha is displayed it is in the formof image so it will be diffiult for robots to detect but easy for human beings*/
header("Content-type:image/png");   

imagepng($img);         // finally image is displayed

?>
